// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSJ6Tntbu9MNDfeU8A6QtPhiQZbqVpZoo',
    appId: '1:582674881640:web:ff76333a9639dca7092fdd',
    messagingSenderId: '582674881640',
    projectId: 'count2infinity-2810c',
    authDomain: 'count2infinity-2810c.firebaseapp.com',
    storageBucket: 'count2infinity-2810c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gsgFQ_UbvbxTqrzoUKjf4yn8t29mJr4',
    appId: '1:582674881640:android:dd5590307cc6e26c092fdd',
    messagingSenderId: '582674881640',
    projectId: 'count2infinity-2810c',
    storageBucket: 'count2infinity-2810c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXW9haUcaTq-Xa6L6_yrk7IpMaY1AeYbg',
    appId: '1:582674881640:ios:d6113e0a92416edf092fdd',
    messagingSenderId: '582674881640',
    projectId: 'count2infinity-2810c',
    storageBucket: 'count2infinity-2810c.appspot.com',
    iosBundleId: 'com.changamuka.pharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXW9haUcaTq-Xa6L6_yrk7IpMaY1AeYbg',
    appId: '1:582674881640:ios:d6113e0a92416edf092fdd',
    messagingSenderId: '582674881640',
    projectId: 'count2infinity-2810c',
    storageBucket: 'count2infinity-2810c.appspot.com',
    iosBundleId: 'com.changamuka.pharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSJ6Tntbu9MNDfeU8A6QtPhiQZbqVpZoo',
    appId: '1:582674881640:web:df3bb6583f716231092fdd',
    messagingSenderId: '582674881640',
    projectId: 'count2infinity-2810c',
    authDomain: 'count2infinity-2810c.firebaseapp.com',
    storageBucket: 'count2infinity-2810c.appspot.com',
  );

}